linkedin:
  label: LinkedIn
  permalink: /linkedin
  description: Posts related to my LinkedIn presence

docusaurus:
  label: Docusaurus
  permalink: /docusaurus
  description: Posts related to working with Docusaurus configuration and components
react: 
  label: React
  permalink: /react
  description: Posts to do with the React ecosystem
storybook:
  label: Storybook
  permalink: /storybook
  description: Posts to do with configuring or using Storybook
vscode:
  label: Visual Studio Code
  permalink: /vscode
  description: Posts to do with IDE Visual Studio Code

coolServices:
  label: Cool Services
  permalink: cool-services
  description: Posts about cool services I found

automation:
  label: Automation
  permalink: /automation
  description: Posts having to do with automating tasks 
troubleshooting:
  label: Trouble-shooting
  permalink: /troubleshooting
  description: Posts having to do with solving problems

formatting:
  label: Formatting/Styles/CSS
  permalink: /formatting
  description: Posts to do with configuring styles and formatting
testing:
  label: Testing
  permalink: /testing
  description: Posts to do with tests
infrastructure:
  label: Infrastructure
  permalink: /infrastructure
  description: Posts to do with setup and maintenance for Repositories, builds, etc.
graphics:
  label: Graphics, Icons & Logos
  permalink: /graphics
  description: Posts to do with created visual elements
brand:
  label: My Brand
  permalink: /brand
  description: Posts to do with developing my personal brand
ci-cd:
  label: CI/CD
  permalink: ci-cd
  description: Posts to do with Continuous Integration and Deployment
integration:
  label: Integration
  permalink: /integration
  description: Posts to do with integrating different systems and services

process:
  label: Process
  permalink: process
  description: changes in process -- project management, tooling, etc.

ai:
  label: Artificial Intelligence
  permalink: /ai
  description: Posts to do with artificial intelligence applications
nova:
  label: Nova
  permalink: /nova
  description: Posts to do with my AI code assistant, Nova (as a project)

customComponents:
  label: Custom Docusaurus Components
  permalink: /custom-components
  description: Posts to do with components I've developed to extend Docusaurus functionallity

svg:
  label: SVG
  permalink: /svg
  description: Posts to do with the SVG format

personal:
  label: personal
  permalink: /personal
  description: Posts of a personal nature
